<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [Mapnik-users] Generate_image.py seems to take wrong longitudes
   </TITLE>
   <LINK REL="Index" HREF="http://lists.berlios.de/pipermail/mapnik-users/2008-March/index.html" >
   <LINK REL="made" HREF="mailto:mapnik-users%40lists.berlios.de?Subject=Re%3A%20%5BMapnik-users%5D%20Generate_image.py%20seems%20to%20take%20wrong%20longitudes&In-Reply-To=%3CCC197224AC75CE4DB23F739B16891B86E33D4D%40tikka.haapa.mmm.fi%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="000754.html">
   <LINK REL="Next"  HREF="000757.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[Mapnik-users] Generate_image.py seems to take wrong longitudes</H1>
    <B>Rahkonen Jukka</B> 
    <A HREF="mailto:mapnik-users%40lists.berlios.de?Subject=Re%3A%20%5BMapnik-users%5D%20Generate_image.py%20seems%20to%20take%20wrong%20longitudes&In-Reply-To=%3CCC197224AC75CE4DB23F739B16891B86E33D4D%40tikka.haapa.mmm.fi%3E"
       TITLE="[Mapnik-users] Generate_image.py seems to take wrong longitudes">Jukka.Rahkonen at mmmtike.fi
       </A><BR>
    <I>Sun Mar 30 23:02:30 CEST 2008</I>
    <P><UL>
        <LI>Previous message: <A HREF="000754.html">[Mapnik-users] Fwd:  [mapnik 0.5] Rendering SVG problem
</A></li>
        <LI>Next message: <A HREF="000757.html">[Mapnik-users] Generate_image.py seems to take wrong longitudes
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#756">[ date ]</a>
              <a href="thread.html#756">[ thread ]</a>
              <a href="subject.html#756">[ subject ]</a>
              <a href="author.html#756">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Hi,

I stopped my trials with rendering OSM maps to epsg:2393 projection with Mapnik and generate_image.py utility.
Instead, I have been trying to learn first how to make maps in default epsg:900913 projection.  Unfortunately, however closely I try to follow the instructions I am always getting maps which have different east-west extents than I am giving as parameters in the generate_image.py script.  

My environment:
- Python 2.5
- Mapnik Windows binaries from:
<A HREF="http://download.berlios.de/mapnik/mapnik_win32_py25-0.5.0.zip">http://download.berlios.de/mapnik/mapnik_win32_py25-0.5.0.zip</A>)
- Generate_image.py downloaded from:
<A HREF="http://svn.openstreetmap.org/applications/rendering/mapnik/generate_image.py">http://svn.openstreetmap.org/applications/rendering/mapnik/generate_image.py</A>)
- OSM data downloaded from:
<A HREF="http://download.geofabrik.de/osm/europe/finland.osm.bz2">http://download.geofabrik.de/osm/europe/finland.osm.bz2</A>
- OSM data uploaded to PostGIS with osm2pgsql.exe (WIndows binaries)
Upload done with options:
osm2pgsql -d postgis -p osm_g -m finland.osm.bz2
- osm.xml downloades from:
<A HREF="http://svn.openstreetmap.org/applications/rendering/mapnik/osm.xml">http://svn.openstreetmap.org/applications/rendering/mapnik/osm.xml</A>

In addition I have downloaded and installed symbol files, shoreline data and World boundaries as advised in:
<A HREF="http://svn.openstreetmap.org/applications/rendering/mapnik/install.txt">http://svn.openstreetmap.org/applications/rendering/mapnik/install.txt</A>

All I have changed are PostGIS database connection parameters and paths to shapefiles.  The system works with all the layers and I can generate maps.  The problem is that the resulting maps do not have the same extents as I give in the generate_image.py file as input parameters.

For example, if I give these ll extents in generate_image.py:
  ll = (24.0,60.0,25.0,61.0)

the resulting map actually covers this area:
ll (23.4841,60.0,25.5117,61.0)


I have taken the latter coordinates from Information Freeway coordinate display and verified them with GPS.

I have repeated this test by different ll values dozens of times and the result is always the same.  Latitude values in the resulting maps are the same I asked for, but not the longitude values.

Is there anybody out there who could verify if there really is some faulty coordinate transformation used for converting longitudes or am I just doing something wrong?

-Jukka Rahkonen-

</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="000754.html">[Mapnik-users] Fwd:  [mapnik 0.5] Rendering SVG problem
</A></li>
	<LI>Next message: <A HREF="000757.html">[Mapnik-users] Generate_image.py seems to take wrong longitudes
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#756">[ date ]</a>
              <a href="thread.html#756">[ thread ]</a>
              <a href="subject.html#756">[ subject ]</a>
              <a href="author.html#756">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://lists.berlios.de/mailman/listinfo/mapnik-users">More information about the Mapnik-users
mailing list</a><br>
</body></html>
